Use only frontend in top-level
neustartklima/ich-kann-klima pull request #18
Opened 2021-05-19 04:49 UTC by jschirrmacher

Removed server and all stuff not really needed for simplicity (but kept `hackathon` folder for documentation purposes).

ATTENTION: Please remove all `node_modules` folders first and re-install by running `npm install` in the top level folder.

2021-05-19 07:48 UTC, mdrie requested changes
Das mocha Problem löst es ja leider noch nicht. Ich finde diese Änderung nur ok, wenn Du die Aufteilung frontend/server nicht mehr oder anders machen möchtest,

Wenn ich es richtig verstehe, sollte das `dist` Verzeichnis wohl nicht eingecheckt werden. Den Rest habe ich mir ehrlich gesagt nicht im Detail angesehen. Hättest Du das gern?

2021-05-19 15:53 UTC, jschirrmacher commented
Ja, `dist` sollte nicht dabei sein, sollte eigentlich in  `.gitignore` sein. Werd' ich dann korrigieren. Und Konflikte gibt's ja jetzt auch.

2021-05-19 16:11 UTC, jschirrmacher commented
Bezüglich des mocha-Problems: du verwendest doch VSCode, richtig? Hast du die recommended extensions installiert?

2021-05-21 04:16 UTC, jschirrmacher commented
Hi @mdrie , von dir steht noch ein Accept aus, würdest du das noch geben, damit den PR mergen können?

2021-05-22 05:12 UTC, merged